#服务启动端口
server :  
  port :  8081

#数据库配置
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/zhi_tui_bao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: root!!2019
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      timeout: 0
      host: 127.0.0.1
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6379
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
        max-wait: -1
mybatis:
  type-aliases-package: com.xiaour.spring.boot.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: /usr/local/zfb/api/log.log
    level: 
        com.ibatis:DEBUG
        root:DEBUG

    
